# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - '_minutes/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '_minutes/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "main"
  main:
    name: Build, Validate, and Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: specification
            source: ./specification/index.bs
          - name: webdriver-classic
            source: ./specification/webdriver-classic.bs
          - name: window-browser
            source: ./specification/window.browser.bs

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the spec-prod (https://w3c.github.io/spec-prod/)
      # the document is built and validated as a check in the pull request.
      # the document is built and validated, and then deployed to gh-pages branch, when a commit is pushed to the main branch.
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          # Deployment will be available at: https://w3c.github.io/webextensions/specification
          SOURCE: ${{ matrix.source }}
          TOOLCHAIN: 'bikeshed'
          ARTIFACT_NAME: ${{ matrix.name }}
